### ISSUE TITLE
Enable operator prometheus metrics

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-operator#66]
**Is your feature request related to a problem? Please describe.**
Prometheus metrics are currently disabled. Operator health needs to be able to monitored using standard operator metrics from kubebuilder. 

**Describe the solution you'd like**
Enable the metrics by un-commenting prometheus kustomize manifests. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rareddy** [comment]
lets not try to create any issue on this @dhirajsb open in the JIRA as sync turned off

**Comment by tarilabs** [comment]
> lets not try to create any issue on this @dhirajsb open in the JIRA as sync turned off

I don't believe the sync was turned off for this repo 🤔  it should appear in JIRA backlog

**Comment by tarilabs** [comment]
[RHOAIENG-4328](https://issues.redhat.com/browse/RHOAIENG-4328), unfortunately I'm not aware of ways to update GH issues with the JIRA information based on the Source documentation
